#!/usr/bin/env node
// SHINE hook — SessionStart
// Refreshes the auto-sync block inside ~/.claude/CLAUDE.md with the current
// list of enabled plugins and MCP servers, so rule-routing stays accurate
// without the user editing CLAUDE.md by hand.
//
// Strategy:
//   1. Read ~/.claude/settings.json (and user-level ~/.claude.json if present)
//   2. Extract enabledPlugins + mcpServers
//   3. Replace everything between the markers:
//        <!-- shine:plugins:begin --> ... <!-- shine:plugins:end -->
//   4. Never fail the session — always exit 0.

'use strict';

const fs = require('fs');
const path = require('path');

const HOME = process.env.HOME || '~';
const CLAUDE_DIR = path.join(HOME, '.claude');
const CLAUDE_MD = path.join(CLAUDE_DIR, 'CLAUDE.md');
const SETTINGS = path.join(CLAUDE_DIR, 'settings.json');
const USER_CFG = path.join(HOME, '.claude.json');

const BEGIN = '<!-- shine:plugins:begin -->';
const END   = '<!-- shine:plugins:end -->';

function readJson(p) {
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return {}; }
}

function collect() {
  const s = readJson(SETTINGS);
  const u = readJson(USER_CFG);
  const plugins = Object.assign({}, u.enabledPlugins || {}, s.enabledPlugins || {});
  const mcp = Object.assign({}, u.mcpServers || {}, s.mcpServers || {});
  return {
    plugins: Object.keys(plugins).filter(k => plugins[k]).sort(),
    mcp: Object.keys(mcp).sort(),
  };
}

function render({ plugins, mcp }) {
  const lines = [];
  lines.push(BEGIN);
  lines.push('<!-- Auto-generated by hooks/integration-sync.js on SessionStart. Do not edit by hand. -->');
  lines.push('');
  lines.push('### Enabled plugins');
  if (plugins.length === 0) lines.push('_(none)_');
  else plugins.forEach(p => lines.push(`- \`${p}\``));
  lines.push('');
  lines.push('### Connected MCP servers');
  if (mcp.length === 0) lines.push('_(none)_');
  else mcp.forEach(m => lines.push(`- \`${m}\``));
  lines.push('');
  lines.push(END);
  return lines.join('\n');
}

try {
  if (!fs.existsSync(CLAUDE_MD)) process.exit(0);
  const src = fs.readFileSync(CLAUDE_MD, 'utf8');
  const block = render(collect());

  let out;
  if (src.includes(BEGIN) && src.includes(END)) {
    const re = new RegExp(`${BEGIN}[\\s\\S]*?${END}`);
    out = src.replace(re, block);
  } else {
    // append at EOF if markers missing
    out = src.trimEnd() + '\n\n' + block + '\n';
  }

  if (out !== src) fs.writeFileSync(CLAUDE_MD, out);
} catch { /* swallow */ }
process.exit(0);
